# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.cache/wt [current_project]
set_property parent.project_path D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU/data.mem
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU/instructions.mem
}
read_verilog -library xil_defaultlib {
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/alu.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/controller.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/data_memory.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/instr_memory.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/mux2x1.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/reg.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/regfile.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/modules/sign_extend.v
  D:/2018-2/SIMPLE-CPU/KURM-CPU/KURM-CPU.srcs/sources_1/imports/KURM-CPU-master/final_cpu.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top micro_processor -part xc7z020clg484-1


write_checkpoint -force -noxdef micro_processor.dcp

catch { report_utilization -file micro_processor_utilization_synth.rpt -pb micro_processor_utilization_synth.pb }
